{
    'name': 'MC App',
    'version':"18.0.1.0.0",
    'depends': ['base','education_core', 'education_fee','account','education_promotion','contacts'],
    'author': 'Mansoura College',
    'sequence': 100,
    'data': [
        'security/mc_education_security.xml',
        'security/ir.model.access.csv',

        'views/res/mc_res_partner.xml',
        'views/res/mc_res_users.xml',
            

        'views/education/mc_education_main_menu.xml',
        'views/education/mc_ministry_report_menu.xml',
        'views/education/mc_education_institute.xml',
        'views/education/mc_eduaction_class_division.xml',
        'views/education/mc_bus_city.xml',
        'views/education/mc_student_relation.xml',
        'views/education/mc_block_reason.xml',
        'views/education/mc_religion.xml',
        'views/education/mc_education_promotion_form.xml',
        'views/education/mc_academic_year_view.xml',
        'views/education/mc_education_student.xml',
        'views/education/mc_education_application_views.xml',
        'views/education/mc_education_faculty.xml',
        'views/education/mc_online_admission_choose_company_form.xml',
        'views/education/mc_online_admission_application_form.xml',
        'views/education/mc_online_submission.xml',
        'views/education/mc_online_submission_failed.xml',
        'views/education/mc_online_submission_updated_template.xml',
        'views/education/mc_education_stages.xml',
        'views/education/mc_education_class_view.xml',
        'views/education/mc_syllabus_domain.xml',
        'views/education/student_ldap_directory.xml',
        'views/education/mc_rooms.xml',
        'views/education/mc_syllabus.xml',
        'views/education/mc_elective_syllabus_student.xml',
        'views/education/mc_standard_class.xml',
        'views/education/mc_enrollment_per_class.xml',
        'views/education/mc_syllabus_per_class.xml',
        'views/education/mc_team_owners.xml',
        'views/education/mc_subject_department.xml',
        'views/education/mc_prev_school_type.xml',
        #'views/education/mc_education_class_history.xml',

        'views/timetable/mc_education_timetable_schedule.xml',
        'views/timetable/mc_education_timetable.xml',
        'views/timetable/mc_timetable_period_views.xml',
        'views/timetable/mc_timetable.xml',
        
        'views/attendence/mc_education_attendance.xml',
        'views/attendence/mc_education_attendence_lines.xml',
        'views/attendence/mc_student_permitted_absence.xml',
        'views/attendence/mc_student_permitted_absence_reason.xml',

        'views/fee/fee_menus.xml',
        'views/fee/mc_education_fee_structure.xml',
        'views/fee/mc_education_fee_type.xml',
        'views/fee/mc_education_fee_category.xml',
        'views/fee/education_fee_discount_config_category.xml',
        'views/fee/education_fee_discount.xml',
        'views/fee/mc_financial_years.xml',
        'views/fee/mc_fee_bank_account.xml',
        'views/fee/education_financial_schools.xml',
        'views/fee/mc_account_move.xml',

        'wizard/education/mc_student_data_report.xml',
        'wizard/education/mc_student_12d_wizard.xml',
        'wizard/education/mc_student_statistics_report.xml',
        'wizard/education/mc_student_history_report.xml',
        
        'wizard/timetables/timetable_by_calss_wizard.xml',
        'wizard/timetables/timtable_by_teacher_wizard.xml',
        'wizard/timetables/timtable_master_wizard.xml',
        'wizard/timetables/revealer_report_wizard.xml',

        'wizard/attendence/behavior.report.no5.wizard.xml',
        'wizard/attendence/absence_days_wizard.xml',
        'wizard/attendence/class_missing_attendence_wizard.xml',
        'wizard/attendence/students_absence_days_wizard.xml',

        'wizard/fee/treasury_report_wizard.xml',
        'wizard/fee/students_report_wizard.xml',
        'wizard/fee/paid_report_wizard.xml',
        'wizard/fee/ministry_fee_report_wizard.xml',

        'reports/timetable/timetable_reports_view.xml',
        'reports/timetable/template_report_timetable_by_class.xml',
        'reports/timetable/template_report_timetable_by_teacher.xml',
        'reports/timetable/template_report_timetable_master.xml',
        'reports/timetable/template_revealer_reports.xml',

        'reports/attendence/reports_view.xml',
        'reports/attendence/template_behavior_report_no5.xml',
        'reports/attendence/template_absence_days_report.xml',
        'reports/attendence/template_students_absence_days_report.xml',
        'reports/attendence/template_class_missing_attendance_report.xml',


        'reports/education/reports_view.xml',
        'reports/education/template_report_student_data.xml',
        'reports/education/template_report_student_history.xml',
        'reports/education/template_report_student_statistics.xml',
        'reports/education/template_report_student_12d.xml',

        'reports/fee/reports_view.xml',
        'reports/fee/treasury_report_template.xml',
        'reports/fee/paid_report_template.xml',
        'reports/fee/ministry_fee_report_template.xml',
    ],
    'assets': {
        'web.assets_frontend': [],
    },

    'installable': True,
    'application':True,
}
